export const PricingData = [
    {
        id: 0,
        title: "Basic",
        subTitle: "Per user per month",
        description: "Get Started With",
        firstPoint: "Basic profile",
        secondPoint: "Receive bid leads",
        thirdPoint: "Access and download bid documents",
        fourthPoint: "Chatting Apps",
        fifthPoint: "Users service provided",
        sixthPoint: "Admin profile upgrade",
        button: "Singh up",
    },
    {
        id: 1,
        title: "Standaed",
        subTitle: "Per user per month",
        description: "Get Started With",
        firstPoint: "Dashboards",
        secondPoint: "Create contacts",
        thirdPoint: "Send or receive quote requests",
        fourthPoint: "Bid Menagement",
        fifthPoint: "Recevie/sumbit  bids and quotes",
        sixthPoint: "Limited cloud bids and quotes",
        button: "Singh up",
    },
    {
        id: 2,
        title: "Premium",
        subTitle: "Per user per month",
        description: "Get Started With",
        firstPoint: "Create amd share Smart profile",
        secondPoint: "In app Communication",
        thirdPoint: "Search leads from members",
        fourthPoint: "Be found in search",
        fifthPoint: "Get reviews on smart profile",
        sixthPoint: "Sufficient cloud storage (100GB  included for free, and additional cost there on)",
        button: "Singh up",
    },
]